### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by anselmbradford**
Updates readme to include more information about dependencies and how to install them.
## Additions
- Adds dependencies section.
- Adds instruction for `cd` into project working directory.
## Changes
- Modifies copy to specify the type of tech stack npm and bower are installing.
## Notes
- Not 100% sure if SASS needs to be installed too or if the compass gem will handle that.

### CODE REVIEW

**Comment by TheSavior** [comment]
Thanks for the improvement to the docs!

I believe grunt-cli could just be installed as an npm dependency via package.json. That would then enable the npm scripts to work. You would need grunt-cli on your system to run them manually.

**Comment by anselmbradford** [comment]
Just pushed a slight edit to fix a typo in the Bower directions.

**Comment by anselmbradford** [comment]
> I believe grunt-cli could just be installed as an npm dependency via package.json. That would then enable the npm scripts to work. You would need grunt-cli on your system to run them manually.

Can you clarify what you're saying here? What edits would be needed in this PR?

**Comment by TheSavior** [comment]
If you add `grunt-cli` to dev-dependencies in package.json then you can run `npm install` which will enable us to run `grunt` tasks from npm scripts without having `grunt-cli` installed globally as a pre-requisite. Nothing else needs to change.

**Comment by anselmbradford** [comment]
Gotcha. Would you want to keep the global grunt CLI installation instructions in the dependencies section as well, or remove those?

Also, I noticed that `package.json` runs [`bower install`](https://github.com/webdriverio/webdrivercss-adminpanel/blob/master/package.json#L59) as a post install script. I was going to open a separate issue about that, but I could correct it here. It's listed in the [install section](https://github.com/webdriverio/webdrivercss-adminpanel#install) of the readme, which appears to be redundant since it'll run after `npm install`, right? 

I would kind of lean toward removing `bower install` from `package.json` and leaving it as a step in the installation instructions, as I think as a postinstall script you couldn't do things like `sudo bower install` (maybe that's edge case, but I found I needed to do that in a vagrant box to create modules directory).

**Comment by christian-bromann** [comment]
> I would kind of lean toward removing bower install from package.json and leaving it as a step in the installation instructions

yes, I like that idea

**Comment by anselmbradford** [comment]
Pushed an update https://github.com/anselmbradford/webdrivercss-adminpanel/commit/3e7ac6b019724141b89a2e0314c4402962c8a86e. Let me know if that looks good and I can squash the commits.

**Comment by christian-bromann** [comment]
Sweet! Thanks!
And sorry for the late response

**Pull request merged**
